<?xml version="1.0" encoding="UTF-8"?>

<!-- Descripción WSDL de la clase Hola Mundo. -->

<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
			 xmlns:tns="urn:Gato_B12037_B10141"
			 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
			 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			 xmlns:soap-enc="http://schemas.xmlsoap.org/soap/encoding/"
			 name="Gato_B12037_B10141"
			 targetNamespace="urn:Gato_B12037_B10141">
	
	<types>
		<xsd:schema targetNamespace="urn:Gato_B12037_B10141"/>
	</types>
	
	<message name="jugarIn"/>
	
	<message name="jugarOut"/>
	
	<portType name="Gato_B12037_B10141Port">
		<operation name="jugar">
			<documentation>Servidor::jugar() Permite jugar gato.</documentation>
			<input message="tns:jugarIn"/>
			<output message="tns:jugarOut"/>
		</operation>	
	</portType>
	
	<binding name="Gato_B12037_B10141Binding" type="tns:Gato_B12037_B10141Port">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		
		<operation name="jugar">
			<soap:operation soapAction="urn:Gato_B12037_B10141#Servidor#jugar"/>
			<input>
				<soap:body use="encoded"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
						   namespace="urn:Gato_B12037_B10141"/>
			</input>
			<output>
				<soap:body use="encoded"
				           encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
						   namespace="urn:Gato_B12037_B10141"/>
			</output>
		</operation>
	</binding>
		 
	<service name="Gato_B12037_B10141Service">
		<port name="Gato_B12037_B10141Port" binding="tns:Gato_B12037_B10141Binding">
			<soap:address location="http://titanic.ecci.ucr.ac.cr/~eb10141/tic_tac_toe/"/>
		</port>
	</service>
</definitions>